publisher:
  name: Bonfida
  address: ''
  website: https://bonfida.org
  email: contact@bonfida.com
  media:
    - purpose: icon
      uri: /images/fida-icon.png
app:
  name: SNS Manager
  address: ''
  android_package: org.bonfida.sns_manager
  urls:
    license_url: https://github.com/Bonfida/sns-manager/blob/master/LICENSE
    privacy_policy_url: https://github.com/Bonfida/sns-manager/blob/master/PRIVACY.md
    website: https://sns.id
  media:
    - purpose: icon
      uri: /favicon.svg
release:
  address: ''
  media:
    - purpose: icon
      uri: ../assets/dapp-store/fida-icon-512x512.png
    - purpose: screenshot
      uri: ../assets/dapp-store/screenshots/homescreen-1080x1920.png
    - purpose: screenshot
      uri: ../assets/dapp-store/screenshots/domains-search-1080x1920.png
    - purpose: screenshot
      uri: ../assets/dapp-store/screenshots/domain-profile-1080x1920.png
    - purpose: screenshot
      uri: ../assets/dapp-store/screenshots/cart-domains-1080x1920.png
    - purpose: screenshot
      uri: ../assets/dapp-store/screenshots/cart-payment-1080x1920.png
  files:
    - purpose: install
      uri: <<RELATIVE_PATH_TO_APK>>
  catalog:
    en-US:
      name: SNS Manager
      short_description: All-in-one tool for SNS
      long_description: Your all-in-one tool for handling Solana Name Service (SNS) domains
      new_in_version: SNS Manager release!
